# Generated by Django 3.0.7 on 2020-06-10 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Foster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('looking_to_foster', models.BooleanField(blank=True, default=False, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=55)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=20)),
                ('zip', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('user__date_joined'), nulls_last=True),),
            },
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=10)),
                ('fixed_date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='')),
                ('breed_id', models.IntegerField()),
                ('adopted_date', models.DateField(blank=True, null=True)),
                ('adopted_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fosteriteapp.Foster')),
                ('bonded_pair_cat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fosteriteapp.Cat')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fosteriteapp.Foster')),
            ],
            options={
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True, nulls_last=True),),
            },
        ),
    ]
