# Generated by Django 3.0.7 on 2020-06-10 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fosteriteapp', '0002_adoptionstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='adoption_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='fosteriteapp.AdoptionStatus'),
        ),
    ]
