# Generated by Django 3.0.7 on 2020-06-10 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fosteriteapp', '0003_cat_adoption_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Litter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fosteriteapp.Cat')),
            ],
        ),
    ]
