# Generated by Django 3.0.7 on 2020-06-10 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fosteriteapp', '0005_auto_20200610_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weighing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fosteriteapp.Cat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fosteriteapp.Foster')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('fvrcp1', models.BooleanField()),
                ('fvrcp2', models.BooleanField()),
                ('rabies', models.BooleanField()),
                ('date', models.DateField()),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fosteriteapp.Cat')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('date', models.DateField()),
                ('tested_positive', models.BooleanField()),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fosteriteapp.Cat')),
            ],
        ),
    ]
