# Generated by Django 3.0.7 on 2020-06-10 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fosteriteapp', '0006_test_vaccination_weighing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Litter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fosteriteapp.Cat')),
            ],
        ),
        migrations.AddField(
            model_name='cat',
            name='litter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fosteriteapp.Litter'),
        ),
    ]
