# Generated by Django 3.0.7 on 2020-06-11 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fosteriteapp', '0007_auto_20200610_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccination',
            name='name',
        ),
        migrations.AlterField(
            model_name='cat',
            name='adopted_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fosteriteapp.Foster'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
