# Generated by Django 3.0.7 on 2020-06-11 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fosteriteapp', '0009_auto_20200611_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='bonded_pair_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fosteriteapp.Cat'),
        ),
    ]
