# Generated by Django 3.0.7 on 2020-06-12 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fosteriteapp', '0010_auto_20200611_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fosterrelationship',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fosteriteapp.Cat'),
        ),
        migrations.AlterField(
            model_name='fosterrelationship',
            name='foster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fosteriteapp.Foster'),
        ),
    ]
