# Generated by Django 3.0.7 on 2020-06-12 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fosteriteapp', '0011_auto_20200612_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fosteriteapp.Cat'),
        ),
        migrations.AlterField(
            model_name='weighing',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fosteriteapp.Cat'),
        ),
    ]
