# Generated by Django 3.0.7 on 2020-06-12 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fosteriteapp', '0015_auto_20200612_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='breed',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='test',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fosteriteapp.Cat'),
        ),
    ]
